### ISSUE TITLE
Does concat works?

### ISSUE THREAD

**Issue by cojack** [felixfbecker/iterare#15]
I can not find a solution for concat to work, any sugestion?

**Comment by felixfbecker** [comment]
Please give a code sample to reproduce. See the test here:
https://github.com/felixfbecker/iterare/blob/master/src/concat.test.ts

**Comment by cojack** [comment]
@felixfbecker hahaha, I think concat will concat an response from iterator to an another array xD
My misunderstanding :+1:

**Comment by felixfbecker** [comment]
Array is Iterable, so yes, it does
