### ISSUE TITLE
export default needs a fix.

### ISSUE THREAD

**Issue by hemanth** [felixfbecker/iterare#2]
```
> const iterate = require("iterare")
> iterate
{ iterate: [Function: iterate],
  zip: [Function: zip],
  default: [Function: iterate] }
> iterate()
TypeError: iterate is not a function
```

**Comment by felixfbecker** [comment]
Why can't you do `const { iterate } = require('iterare')` or `const iterate = require('iterare').default`?

**Comment by hemanth** [comment]
The defies the purpose of `default`?

The read me also needs a fix? (It suggests `import iterate from 'iterare'`)

BTW just covered this module [here](https://nmotw.in/iterare/).

**Comment by felixfbecker** [comment]
But `import iterate from 'iterare'` is 100% correct if you use a transpiler like Babel or TypeScript.
If you use standard Node `require()`, you need to use `.default` or `.iterate`.
The entry point exports multiple functions, for example also `zip`. If`module.exports` was the `iterate` function, then `zip` would have to be a property on that.

**Comment by hemanth** [comment]
Makes sense.
