### ISSUE TITLE
Benchmark ~ hugeSet is huge

### ISSUE THREAD

**Issue by dhoko** [felixfbecker/iterare#3]
Hey, 

Your benchmark is wrong, you wanted to test the lib with a huge collection but you didn't ;)

```js
const hugeSet = new Set(new Array<string>(10000).fill('file:///foo/bar'))
hugeSet.length === 1 ;)
```

### Before (Set.length === 1)
![screenshot at 2017-03-27 14-12-55](https://cloud.githubusercontent.com/assets/713283/24355931/336e0fba-12f8-11e7-9480-31c0ee642d73.png)

### After (Set.length === 10 000)

![screenshot at 2017-03-27 14-17-29](https://cloud.githubusercontent.com/assets/713283/24355946/448a2b12-12f8-11e7-896d-2733bcb0bdf5.png)

Edit:
Maybe we need to update every test too

Edit2 :popcorn: :

```js
const list = [...new Array<string>(10000)].map((e, i) => `file:///foo/bar/${i + 1}`);
// case 1 Set
const hugeSet = new Set(list)

// case 2 Array
const hugeSet = list
```

![screenshot at 2017-03-27 14-27-22](https://cloud.githubusercontent.com/assets/713283/24356287/a519cf7c-12f9-11e7-87a3-607f315566d9.png)

**Comment by felixfbecker** [comment]
Big thanks for noticing! The array constructor for sure can act confusing.
I just modified the benchmark to do:
```ts
const hugeSet = new Set<string>()
for (let i = 0; i < 10000; i++) {
    hugeSet.add('file:///foo/bar')
}
```
which results in a proper `size` set (FYI `Set.prototype.length` does not exist).

But the result of the benchmark is the same:
```
Loop x 2,986,337 ops/sec ±1.62% (87 runs sampled)
iterare x 2,201,494 ops/sec ±1.94% (85 runs sampled)
Array method chain x 331,565 ops/sec ±3.76% (81 runs sampled)
Lodash x 342,131 ops/sec ±1.22% (86 runs sampled)
RxJS x 31,356 ops/sec ±3.29% (50 runs sampled)
Fastest is Loop
```

How did you get the second result?

**Comment by dhoko** [comment]
```js
const testArray = () => {

    const suite = new Suite()

    // Simulate iterating over a very lage Set of strings and applying a filter and a map on it

    const hugeSet = list
    
    /** 
     * ... suites
     */

    suite.on('complete', function (this: Suite) {
        console.log('===> Array');
        console.log('Fastest is ' + this.filter('fastest').map('name' as any))
    })

    suite.run({ async: true })

}

const testSet = () => {

    const suite = new Suite()

    // Simulate iterating over a very lage Set of strings and applying a filter and a map on it

    const hugeSet = new Set(list)
    /**
     * ... suites
     */

    suite.on('complete', function (this: Suite) {
        console.log('===> Set');

        console.log('Fastest is ' + this.filter('fastest').map('name' as any))
        testArray();
    })

    suite.run({ async: true })

}

testSet()

```

Quick&dirty

**Comment by felixfbecker** [comment]
I just fixed the benchmarks in e291b8529881e7e5099bc7aa16bc674fb7248e56.

There was actually a different issue - lodash doesn't support Sets, so the result in the lodash suite was always zero, which is why in your example lodash was faster. Calling `Array.from()` before fixes it. The end result of the benchmark stays largely the same, but thanks anyway for reporting this, having correct benchmarks is very important.

**Comment by dhoko** [comment]
I think instead of doing `Array.from` each time we can move it to a var. `const hugeSetList = Array.from(hugeSet);`

Cf =>
![screenshot at 2017-03-27 15-05-30](https://cloud.githubusercontent.com/assets/713283/24357679/d993f96c-12fe-11e7-85ea-532bf533824b.png)

**Comment by felixfbecker** [comment]
I don't understand, what do you mean with "each time"? Can you please post code (instead of screenshots)? The scenario is filtering and mapping a Set, not an array.

**Comment by dhoko** [comment]
Mea culpa,

```js
suite.add('Array method chain', () => {
    return new Set(
        hugeSetList
            .filter(uri => uri.startsWith('file://'))
            .map(uri => uri.substr('file:///'.length))
    )
})
```

I don't know how does `Suite` work, I think it takes a test callback and runs it multiple times. 
Doing `Array.from` has a cost (_a small one, but you want the benchmark to be fair_ ;) )

**Comment by felixfbecker** [comment]
Yeah, but that is the point of including it. One of the reasons this library is fast is because it does not have to do `Array.from()`, it can just iterate over the Set directly, because Set is an Iterable.
